#!/bin/bash

./cephadm shell ceph fs volume create manila

read -d '' MON_CAPS << EOF
allow r,
allow command "auth del",
allow command "auth caps",
allow command "auth get",
allow command "auth get-or-create"
EOF

./cephadm shell ceph auth get-or-create client.manila mds 'allow *' osd 'allow rw' mon "$MON_CAPS" > ceph.client.manila.keyring

